/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactInquiry {
    id: bigint;
    subject: InquiryType;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export enum InquiryType {
    admissions = "admissions",
    other = "other",
    support = "support",
    general = "general"
}
export interface backendInterface {
    deleteContactInquiry(id: bigint): Promise<void>;
    getAllContactInquiries(): Promise<Array<ContactInquiry>>;
    getContactInquiry(id: bigint): Promise<ContactInquiry>;
    submitContactInquiry(fullName: string, email: string, phone: string, subject: InquiryType, message: string, timestamp: bigint): Promise<void>;
}
import type { ContactInquiry as _ContactInquiry, InquiryType as _InquiryType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteContactInquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactInquiry(arg0);
            return result;
        }
    }
    async getAllContactInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactInquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactInquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInquiry(arg0: bigint): Promise<ContactInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInquiry(arg0);
                return from_candid_ContactInquiry_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInquiry(arg0);
            return from_candid_ContactInquiry_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactInquiry(arg0: string, arg1: string, arg2: string, arg3: InquiryType, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactInquiry(arg0, arg1, arg2, to_candid_InquiryType_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactInquiry(arg0, arg1, arg2, to_candid_InquiryType_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_ContactInquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInquiry): ContactInquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subject: _InquiryType;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}): {
    id: bigint;
    subject: InquiryType;
    fullName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
} {
    return {
        id: value.id,
        subject: from_candid_InquiryType_n4(_uploadFile, _downloadFile, value.subject),
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admissions: null;
} | {
    other: null;
} | {
    support: null;
} | {
    general: null;
}): InquiryType {
    return "admissions" in value ? InquiryType.admissions : "other" in value ? InquiryType.other : "support" in value ? InquiryType.support : "general" in value ? InquiryType.general : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactInquiry>): Array<ContactInquiry> {
    return value.map((x)=>from_candid_ContactInquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_InquiryType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    admissions: null;
} | {
    other: null;
} | {
    support: null;
} | {
    general: null;
} {
    return value == InquiryType.admissions ? {
        admissions: null
    } : value == InquiryType.other ? {
        other: null
    } : value == InquiryType.support ? {
        support: null
    } : value == InquiryType.general ? {
        general: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
