/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryType = IDL.Variant({
  'admissions' : IDL.Null,
  'other' : IDL.Null,
  'support' : IDL.Null,
  'general' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'subject' : InquiryType,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteContactInquiry' : IDL.Func([IDL.Nat], [], []),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getContactInquiry' : IDL.Func([IDL.Nat], [ContactInquiry], ['query']),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, InquiryType, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryType = IDL.Variant({
    'admissions' : IDL.Null,
    'other' : IDL.Null,
    'support' : IDL.Null,
    'general' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'subject' : InquiryType,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteContactInquiry' : IDL.Func([IDL.Nat], [], []),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getContactInquiry' : IDL.Func([IDL.Nat], [ContactInquiry], ['query']),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, InquiryType, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };